version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for python dependency updates every weekday at 08:00 UTC
      interval: "daily"
      time: "08:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday at 08:00 UTC
      interval: "daily"
      time: "08:00"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      # Check for updates to container images every weekday at 08:00 UTC
      interval: "daily"
      time: "08:00"
